### ISSUE TITLE
Update HA to 2025.8.2 breaks the saj-mqtt custom

### ISSUE THREAD

**Issue by stewepylon** [paolosabatino/saj-mqtt-ha#12]
After this update, SAJ-mqtt no longer works.
It seems to be related to the pymodbus constraint that was added.
Removing the requirements in the manifest seems to not be enough.
Reverting to 2025.8.1 restored the functionality.

**Comment by paolosabatino** [comment]
> After this update, SAJ-mqtt no longer works. It seems to be related to the pymodbus constraint that was added. Removing the requirements in the manifest seems to not be enough. Reverting to 2025.8.1 restored the functionality.

Hello,

not enforcing the pymodbus version and letting it use the latest version solves the issue?
Any log produced by HA could be useful to pinpoint the problem

**Comment by Argon007** [comment]
Hello,

I have the same problem. saj_mqtt is working perfectly on 2025.8.1, but is broken on 2025.8.2 because of that pymodbus update:
https://github.com/home-assistant/core/pull/150420

This is what I get in HA:
```
Logger: homeassistant.setup
Source: setup.py:278
First occurred: 16:25:04 (1 occurrence)
Last logged: 16:25:04

Setup failed for custom integration 'saj_mqtt': Requirements for saj_mqtt not found: ['pymodbus==3.5.4'].
```

And this is the logs from within Portainer:
```
2025-09-08 14:25:04.271 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pymodbus==3.5.4: × No solution found when resolving dependencies:

  ╰─▶ Because you require pymodbus==3.5.4 and pymodbus==3.9.2, we can conclude

      that your requirements are unsatisfiable.
```

Any idea how to fix this?

**Comment by Argon007** [comment]
I asked my friend ChatGpt... I changed the manifest file and removed the spefic version requirments to this:
```
{
  "domain": "saj_mqtt",
  "name": "SAJ MQTT",
  "version": "0.1",
  "requirements": [
    "pymodbus"
  ],
  "dependencies": [
    "mqtt"
  ],
  "issue_tracker": "",
  "documentation": "",
  "codeowners": [
    "@paolosabatino",
    "@h3llrais3r"
  ],
  "iot_class": "local_polling",
  "loggers": [
    "saj_mqtt"
  ]
}
```

After this I had another error that it wasn't able to load import "computeCRC":

`2025-09-08 14:30:41.633 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'saj_mqtt': Unable to import component: cannot import name 'computeCRC' from 'pymodbus.utilities' (/usr/local/lib/python3.13/site-packages/pymodbus/utilities.py)`

In sajmqtt.py I had to remove the line:
`from pymodbus.utilities import computeCRC`


And add this:
```
def computeCRC(data: bytes) -> int:
    crc = 0xFFFF
    for pos in data:
        crc ^= pos
        for _ in range(8):
            if crc & 0x0001:
                crc >>= 1
                crc ^= 0xA001
            else:
                crc >>= 1
    return crc

```
And now I see this in the portainer logs:
```
2025-09-08 14:40:31.191 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)

2025-09-08 14:40:31.359 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)

2025-09-08 14:40:31.491 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)

2025-09-08 14:40:41.050 WARNING (MainThread) [custom_components.saj_mqtt] Timeout error: the inverter did not answer in the expected timeout

2025-09-08 14:41:41.192 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)

2025-09-08 14:41:41.342 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)

2025-09-08 14:41:41.495 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)

2025-09-08 14:41:51.049 WARNING (MainThread) [custom_components.saj_mqtt] Timeout error: the inverter did not answer in the expected timeout

2025-09-08 14:42:51.193 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)

2025-09-08 14:42:51.355 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)

2025-09-08 14:42:51.494 ERROR (MainThread) [custom_components.saj_mqtt] Error while handling data_transmission_rsp packet: Unsupported request type: 0x83 (131)
```

So i'm still stuck and in fact I don't know what i'm doing ;-).

**Comment by Argon007** [comment]
Nobody around with knowledge about this to solve the issue?

**Comment by stewepylon** [comment]
I just preferred go back to the August release in this moment. I tried to fix by removing the version but it didn't work. Probably newer version has deprecated or removed something used in the custom app. I will provide logs in the next weeks when I'll have some time for this.

**Comment by stewepylon** [comment]
[sajmqtt.py](https://github.com/user-attachments/files/22311174/sajmqtt.py)

I made some modifications (with ChatGPT help) to the file and it seems working... but I can't guarantee it of course :).
The modifications made:
-removed 3.5.4 from manifest
-CRC function missing → had to include computeCRC.
-CRC values incorrect → fixed by normalizing to 16-bit.
-Wrong byte order → corrected CRC endianness.
-MQTT payload issue → enforced raw byte publishing.

I'm now on HA 2025.9.x

**Comment by stewepylon** [comment]
> Hello,
> 
> not enforcing the pymodbus version and letting it use the latest version solves the issue? Any log produced by HA could be useful to pinpoint the problem

Ciao @paolosabatino ,

after removing version in the manifest and included the ComputeCRC, in the HA logs I had:

-Timeout error: the inverter did not answer in the expected timeout

-Error while handling data_transmission_rsp packet:
unpack_from requires a buffer of at least 77 bytes for unpacking 2 bytes at offset 75 (actual buffer size is 16)

**Comment by paolosabatino** [comment]
Hello!

> -Timeout error: the inverter did not answer in the expected timeout
> -Error while handling data_transmission_rsp packet: unpack_from requires a buffer of at least 77 bytes for unpacking 2 bytes at offset 75 (actual buffer size is 16)

My best guess is that if the buffer size of the response packet is 16 bytes, then something bad happened in the request. Perhaps the CRC has not been computer correctly or there is something else misplaced or wrong in the request that the inverter did not like. The inverter sent back an error packet rather than a proper answer. Error packets are usually a bunch of bytes. 

You may wish to try [this](https://github.com/paolosabatino/saj-mqtt/blob/cad9fcbf90de0f675f622182e0d72a59a6b44d3c/sajmqtt.py#L45) `computeCRC` function, which is correctly working so far. The [other project](https://github.com/paolosabatino/saj-mqtt/tree/main) is also useful to query the inverter via command line

edit: after a quick compare, it  looks to me that CRC endians are swapped

**Comment by Argon007** [comment]
I'm a noob, but for my understanding it seems the problem isn't solved? Is there another way/package/... available to read the values from a SAJ inverter into Home Assistant?

**Comment by stewepylon** [comment]
> I'm a noob, but for my understanding it seems the problem isn't solved? Is there another way/package/... available to read the values from a SAJ inverter into Home Assistant?

Hi @Argon007 ,
the sajmqtt.py I've attached 2 days ago is working fine for me.
You can try it if you want.
The sensor are reporting real data according to my elekeeper app.

<img width="474" height="403" alt="Image" src="https://github.com/user-attachments/assets/11ee2a68-94ae-4934-951c-bc8fd906c341" />

**Comment by h3llrais3r** [comment]
I've completely rewritten the integration (according to new HA standards) and with setup through GUI.
I also got rid of the pymodus dependency, so I suggest to try it.
You can find it at https://github.com/h3llrais3r/ha-saj-h1-mqtt
I've been running it for a couple of months now, without any issues, even with the most recent version of ha.
I've also renamed it so it's more clear that it's only for saj h1 inverter, over mqtt.
(I've included Paolo as one of the original code owners in my new repo 😉) as he created the original version.

Attention: switching to my integration will result in loss of existing historical data, as also sensors are renamed.
Please read the readme carefully. Setup is now only possible via GUI, with different options.
If you have an issue with my integration, please open an issue in my repo, because I don't often check this repo anymore.

**Comment by miquelbotanch** [comment]
Would not be nice to make a pull request and keep this working ?

**Comment by h3llrais3r** [comment]
Sorry, I won't make a PR on the old code anymore... I spend a lot of time for rewriting it, so I can only suggest trying my new version, with a lot of improvements.
If you really want this version to be fixed, I suggest to create the PR yourself and test it. [This](https://github.com/h3llrais3r/ha-saj-h1-mqtt/pull/1/commits/57f56201028375ef315aaa5f8acc2f386b787ecf) commit shows you the changes for getting rid of the pymodbus dependency.

**Comment by Argon007** [comment]
Moved over to @h3llrais3r his add-on and it's working perfectly. I was able to maintain the historical values from the sensor so my Energy dashboard is also still intact. Now I can update Home Assistant again to the latest version. Thanks!
